### ISSUE TITLE
release v0.1 issue: include user selection of spatial extent and counterfactual

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-sws-r-targets#1]
the pipeline should allow A) jurisidiction (e.g. WA) and B) counterfactual (e.g. PM2.5 reduced to 5 or below as per WHO guidelines 2021)

**Comment by cassandrayuen** [comment]
Done, set in global variable state (jurisdiction) and counterfactual controlled in `do_env_counterfactual` function.
