### ISSUE TITLE
incorporate leaflet as a target instead of in main.R

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-sws-r-targets#2]
This is 'nice-to-have' but not 'have-to-have' for release v0.1

**Comment by cassandrayuen** [comment]
Target leaflet_an produces a leaflet map. Note the provider tiles cannot be added within the target as it launches a subprocess and cannot find the temp file afterwards. Retrieve the leaflet map and add the provider tiles outside the pipeline: `tar_read(leaflet_an)  %>% addProviderTiles("CartoDB.Positron")`.
